Repository TechCell-Project/techcell-web-client-v2, pull requests merged in 2024-04, with the labels that each got.

#1 feat(ui): ✨ add user's UI footer interface
  app/layout.tsx
  components/navigation/footer/index.tsx
Labels: size/L

#2 Customize UI
  app/layout.tsx
  app/page.tsx
  components/home/home-page.tsx
  components/home/swiper-carousel.tsx
  components/navigation/footer/index.tsx
  constants/common.ts
  constants/nav.ts
  public/banner.png
Labels: size/L

#4 footer UI
  components/navigation/footer/index.tsx
Labels: size/L

#8 Auth handler
  apiRequests/auth.ts
  app/(auth)/dang-xuat/page.tsx
  app/api/auth-client/logout/route.ts
  app/api/auth-client/refresh/route.ts
  app/api/auth-client/route.ts
  app/layout.tsx
  app/loading.tsx
  app/page.tsx
  components/auth/auto-refresh-token.tsx
  components/auth/login-form.tsx
  components/common/max-width-wrapper.tsx
  components/common/modals/address-modal.tsx
  components/home/home-page.tsx
  components/navigation/header/button-logout.tsx
  components/navigation/header/header-icon.tsx
  components/profile/profile-form.tsx
  components/profile/profile.tsx
  components/ui/modal.tsx
  components/ui/toast.tsx
  config.ts
  constants/error.ts
  hooks/useAddressModal.tsx
  lib/http.ts
  package.json
  providers/app-provider.tsx
  providers/modal-provider.tsx
  validationSchemas/common.schema.ts
  yarn.lock
Labels: size/XL

#9 feat(components): ✨ add profile address
  apiRequests/address.ts
  apiRequests/auth.ts
  apiRequests/index.ts
  app/(auth)/confirm-email/page.tsx
  app/(auth)/dang-ky-tai-khoan/layout.tsx
  app/(auth)/dang-nhap/layout.tsx
  app/(auth)/dang-xuat/page.tsx
  app/(auth)/layout.tsx
  app/(need-authenticated)/ho-so/page.tsx
  app/api/auth-client/refresh/route.ts
  app/globals.css
  app/loading.tsx
  components/auth/auto-refresh-token.tsx
  components/auth/login-form.tsx
  components/auth/register-form.tsx
  components/common/form/input-combobox.tsx
  components/common/form/input-select.tsx
  components/common/loading-server.tsx
  components/common/modals/address-modal.tsx
  components/navigation/header/button-logout.tsx
  components/navigation/header/header-icon.tsx
  components/profile/address-form.tsx
  components/profile/profile-form.tsx
  components/profile/profile.tsx
  components/ui/command.tsx
  components/ui/image-upload.tsx
  components/ui/popover.tsx
  components/ui/scroll-area.tsx
  components/ui/select.tsx
  constants/common.ts
  constants/error.ts
  constants/index.ts
  hooks/useAddressModal.tsx
  lib/http.ts
  lib/utils.ts
  package.json
  providers/auth-store-provider.tsx
  providers/modal-provider.tsx
  stores/auth.store.ts
  validationSchemas/profile.schema.ts
  yarn.lock
Labels: size/XXL

#10 feat(components): :zap: re-built updProfile, applied ssr fetching logic
  apiRequests/auth.ts
  app/(auth)/mat-khau-moi/layout.tsx
  app/(auth)/mat-khau-moi/page.tsx
  app/(auth)/quen-mat-khau/layout.tsx
  app/(auth)/quen-mat-khau/page.tsx
  app/(need-authenticated)/ho-so/page.tsx
  app/globals.css
  app/layout.tsx
  components/auth/forgot-password-form.tsx
  components/auth/login-form.tsx
  components/auth/new-password-form.tsx
  components/common/form/input-password.tsx
  components/common/modals/address-modal.tsx
  components/profile/address-form.tsx
  components/profile/password-form.tsx
  components/profile/profile-form.tsx
  components/profile/profile.tsx
  components/ui/separator.tsx
  constants/enum.ts
  constants/error.ts
  hooks/useAddressModal.ts
  lib/axios/index.ts
  lib/http.ts
  package.json
  providers/modal-provider.tsx
  validationSchemas/auth.schema.ts
  validationSchemas/profile.schema.ts
  yarn.lock
Labels: size/XXL

#11 feat(ui): ✨ add ui for `list products` and `cart`
  .coderabbit.yaml
  apiRequests/brand.ts
  apiRequests/product.ts
  app/(need-authenticated)/gio-hang/layout.tsx
  app/(need-authenticated)/gio-hang/page.tsx
  app/favicon.ico
  app/layout.tsx
  app/page.tsx
  common/model.ts
  components/brands/brand.tsx
  components/brands/models/brand.ts
  components/brands/models/index.ts
  components/cart/cart-empty.tsx
  components/cart/cart-page.tsx
  components/cart/cart-suggest.tsx
  components/cart/list-product-cart.tsx
  components/home/home-page.tsx
  components/home/list-product.tsx
  components/navigation/footer/index.tsx
  components/ui/button.tsx
  components/ui/checkbox.tsx
  constants/common.ts
  constants/enum.ts
  constants/phone-test.ts
  package.json
  public/cart-empty.png
  public/phone-test/15-base.jpg
  public/phone-test/15-pro.jpg
  public/phone-test/15-promax.jpg
  public/phone-test/flip5-base.jpg
  public/phone-test/flip5-plus.jpg
  public/phone-test/flip5-ultra.jpg
  tsconfig.json
  utilities/func.util.ts
  utilities/session.util.ts
  yarn.lock
Labels: size/XL

#12 Update list product UI
  apiRequests/product.ts
  components/home/list-product.tsx
  constants/phone-test.ts
  package.json
  public/phone-test/IpXS.webp
  public/phone-test/ip11.webp
  public/phone-test/ip11pro.webp
  public/phone-test/ip12.webp
  public/phone-test/ip12mini.webp
  public/phone-test/ip12pro.webp
  public/phone-test/ip13.webp
  public/phone-test/ip13mini.webp
  public/phone-test/ip13pro.webp
  public/phone-test/ip14.webp
  public/phone-test/ip14Plus.webp
  public/phone-test/ip14pro.webp
  public/phone-test/ipX.webp
  public/phone-test/ipXR.webp
  utilities/func.util.ts
  yarn.lock
Labels: size/XL

#14 feat(components): ✨ released update user address
  apiRequests/auth.ts
  app/layout.tsx
  components/common/form/input-combobox.tsx
  components/common/modals/address-modal.tsx
  components/navigation/header/button-logout.tsx
  components/navigation/header/header-icon.tsx
  components/navigation/header/index.tsx
  components/profile/address-form.tsx
  components/profile/address-list.tsx
  components/profile/profile-form.tsx
  components/profile/profile.tsx
  components/ui/badge.tsx
  constants/common.ts
  lib/utils.ts
  package.json
  providers/app-provider.tsx
  providers/modal-provider.tsx
  tailwind.config.ts
  yarn.lock
Labels: size/XL

#15 Product detail
  app/(need-authenticated)/chi-tiet-san-pham/layout.tsx
  app/(need-authenticated)/chi-tiet-san-pham/page.tsx
  components/home/list-product.tsx
  components/product/choose-product-variation.tsx
  components/product/detail-product-page.tsx
  components/product/dialog-specifications.tsx
  components/product/outstanding-features-product.tsx
  components/product/swiper-detail-product.tsx
  components/product/table-specification-detail.tsx
  components/product/table-specifications.tsx
  components/ui/table.tsx
  config.ts
  constants/common.ts
  constants/product-detail.ts
  hooks/useSkipFirstRender.ts
  package.json
  styles/dialog.css
  styles/swiper.css
  tailwind.config.ts
  tsconfig.json
  utilities/func.util.ts
  yarn.lock
Labels: size/XXL

#17 feat(components): ✨ build products page (demo)
  apiRequests/brand.ts
  apiRequests/product.ts
  app/(public)/chi-tiet-san-pham/layout.tsx
  app/(public)/chi-tiet-san-pham/page.tsx
  app/(public)/danh-sach-san-pham/layout.tsx
  app/(public)/danh-sach-san-pham/page.tsx
  app/page.tsx
  components/auth/login-form.tsx
  components/brands/brandscrolling.tsx
  components/common/breadcrumbs.tsx
  components/common/form/input-combobox.tsx
  components/common/product-card/normal-card-button.tsx
  components/common/product-card/normal-card.tsx
  components/ui/breadcrumb.tsx
  components/ui/skeleton.tsx
  constants/common.ts
  constants/validApiParams.ts
  lib/utils.ts
Labels: size/XL

#16 Add home page interface and start shopping cart
  apiRequests/brand.ts
  apiRequests/cart.ts
  app/layout.tsx
  app/page.tsx
  components/auth/login-form.tsx
  components/brands/brand.tsx
  components/brands/models/brand.ts
  components/cart/models/cart.ts
  components/cart/models/index.ts
  components/home/home-page.tsx
  components/home/list-product-hot.tsx
  components/home/list-product.tsx
  components/navigation/header/index.tsx
  constants/enum.ts
  public/hot-sale.jpg
Labels: size/L

#18 update searching products
  apiRequests/brand.ts
  apiRequests/product.ts
  app/(public)/danh-sach-san-pham/layout.tsx
  app/(public)/danh-sach-san-pham/page.tsx
  app/page.tsx
  components/brands/brand.tsx
  components/common/breadcrumbs.tsx
  components/common/pagination/pagination-bar.tsx
  components/common/searchbar/search-bar.tsx
  components/navigation/footer/index.tsx
  components/navigation/header/index.tsx
  components/navigation/header/left-nav.tsx
  components/products/result-search.tsx
  constants/validApiParams.ts
  lib/utils.ts
  validationSchemas/common.schema.ts
Labels: size/L

#20 feat(responsive) ✨ update for home page
  app/(public)/danh-sach-san-pham/page.tsx
  components/brands/brand.tsx
  components/home/list-product-hot.tsx
  components/home/list-product.tsx
  components/navigation/footer/index.tsx
  styles/swiper.css
Labels: size/L

#23 feat(components): ✨ update product detail page
  app/(public)/chi-tiet-san-pham/[id]/layout.tsx
  app/(public)/chi-tiet-san-pham/[id]/page.tsx
  app/(public)/chi-tiet-san-pham/layout.tsx
  app/(public)/chi-tiet-san-pham/page.tsx
  app/(public)/danh-sach-san-pham/page.tsx
  app/custom.css
  components/brands/brand.tsx
  components/common/max-width-wrapper.tsx
  components/common/pagination/pagination-bar.tsx
  components/common/product-card/normal-card.tsx
  components/common/product-price.tsx
  components/home/swiper-carousel.tsx
  components/navigation/footer/index.tsx
  components/navigation/header/header-icon.tsx
  components/product/choose-product-variation.tsx
  components/product/detail-product-page.tsx
  components/product/dialog-specifications.tsx
  components/product/outstanding-features-product.tsx
  components/product/product-detail.tsx
  components/product/product-img-slider.tsx
  components/product/select-product-variation.tsx
  components/product/swiper-detail-product.tsx
  components/product/table-specification-detail.tsx
  components/product/table-specifications.tsx
  components/products/result-search.tsx
  constants/validApiParams.ts
  package.json
  tailwind.config.ts
  yarn.lock
Labels: size/XXL

#24 feat(components): ✨ complete update product address
  apiRequests/cart.ts
  apiRequests/index.ts
  apiRequests/product.ts
  app/(public)/chi-tiet-san-pham/[id]/page.tsx
  components/auth/login-form.tsx
  components/common/form/input-combobox.tsx
  components/common/product-card/normal-card.tsx
  components/product/button-buy.tsx
  components/product/product-detail.tsx
  components/product/product-img-slider.tsx
  components/product/select-product-variation.tsx
  components/profile/address-list.tsx
  components/profile/profile.tsx
  components/ui/image-upload.tsx
  components/ui/radio-group.tsx
  lib/http.ts
  next.config.mjs
  package.json
  yarn.lock
Labels: size/XL

#21 feat(auth): :sparkles: add auth social with google
  .vscode/settings.json
  apiRequests/auth.ts
  app/layout.tsx
  components/auth/login-form.tsx
  components/auth/social.tsx
  package.json
  yarn.lock
Labels: size/L

#25 Improve perfomance when searching with Vietnamese keyword
  components/auth/login-form.tsx
  components/auth/social.tsx
  components/common/form/input-combobox.tsx
  lib/http.ts
  package.json
  yarn.lock
Labels: size/M

#22 update responsive home page
  components/brands/brand.tsx
  components/home/list-product-hot.tsx
  components/home/list-product.tsx
  components/navigation/footer/index.tsx
Labels: size/M

#27 Page brand
  apiRequests/cart.ts
  app/(public)/danh-sach-san-pham/page.tsx
  app/(public)/thuong-hieu/layout.tsx
  app/(public)/thuong-hieu/page.tsx
  components/brands/brandscrolling.tsx
  components/cart/cart-empty.tsx
  components/cart/cart-suggest.tsx
  components/cart/list-product-cart.tsx
  components/home/banner-page.tsx
  components/home/home-page.tsx
  components/home/list-product-hot.tsx
  constants/enum.ts
  public/banner/banner.png
  public/banner/banner2.jpg
  public/banner/banner3.jpg
  styles/banner.css
  styles/product.css
  tsconfig.json
Labels: size/L

#29 update user cart functionallity
  apiRequests/cart.ts
  apiRequests/product.ts
  app/(need-authenticated)/gio-hang/page.tsx
  app/(public)/danh-sach-san-pham/action.ts
  components/cart/card-product-cart.tsx
  components/cart/cart-empty.tsx
  components/cart/cart-page.tsx
  components/cart/cart-product-skeleton.tsx
  components/cart/list-product-cart.tsx
  components/cart/product-cart.tsx
  components/cart/update-product-cart.tsx
  components/common/button-back.tsx
  components/navigation/header/header-icon.tsx
  components/product/button-buy.tsx
  components/profile/address-list.tsx
  package.json
  types/cart.type.ts
  yarn.lock
Labels: size/XL

#30 feat(components): :sparkles: update products page infinite scroll
  apiRequests/brand.ts
  app/(public)/chi-tiet-san-pham/[id]/page.tsx
  app/(public)/danh-sach-san-pham/action.ts
  app/(public)/danh-sach-san-pham/page.tsx
  components/common/breadcrumbs.tsx
  components/common/loading-server.tsx
  components/navigation/header/header-icon.tsx
  components/products/load-more.tsx
  package.json
  yarn.lock
Labels: size/L

#31 update UI homePage, productDetail
  app/(need-authenticated)/gio-hang/page.tsx
  app/(public)/chi-tiet-san-pham/[id]/page.tsx
  app/(public)/thuong-hieu/page.tsx
  app/page.tsx
  components/brands/brand.tsx
  components/common/product-card/normal-card.tsx
  components/home/banner-page.tsx
  components/home/home-page.tsx
  components/home/list-product-hot.tsx
  components/home/list-product.tsx
  components/product/dialog-specifications.tsx
  components/product/outstanding-features-product.tsx
  components/product/product-detail.tsx
  components/product/similar-product.tsx
  constants/common.ts
  styles/product.css
Labels: size/XL

#32 payment_page
  app/(need-authenticated)/thanh-toan/chi-tiet-don-hang/layout.tsx
  app/(need-authenticated)/thanh-toan/chi-tiet-don-hang/page.tsx
  app/(need-authenticated)/thanh-toan/layout.tsx
  app/(need-authenticated)/thanh-toan/page.tsx
  components/cart/cart-suggest.tsx
  components/navigation/footer/index.tsx
  components/order/address-order.tsx
  components/order/order-list-product.tsx
  components/order/order-preview.tsx
  components/order/payment_method_list.tsx
  components/order/shipping-info-order.tsx
  constants/phone-test.ts
  public/payment_img/1.png
  public/payment_img/2.webp
  public/payment_img/3.webp
  public/payment_img/4.webp
Labels: size/XL

#33 feat(components): ✨ update payment page (in progress...)
  apiRequests/cart.ts
  apiRequests/index.ts
  apiRequests/order.ts
  apiRequests/product.ts
  app/(auth)/dang-xuat/page.tsx
  app/(need-authenticated)/gio-hang/page.tsx
  app/(need-authenticated)/thanh-toan/layout.tsx
  app/(need-authenticated)/thanh-toan/page.tsx
  app/(public)/chi-tiet-san-pham/[id]/page.tsx
  app/layout.tsx
  app/page.tsx
  components/cart/list-product-cart.tsx
  components/home/home-page.tsx
  components/home/list-product-hot.tsx
  components/navigation/header/header-icon.tsx
  components/order/order-preview.tsx
  components/order/shipping-info-order.tsx
  components/product/similar-product.tsx
  components/profile/address-form.tsx
  components/profile/address-list.tsx
  constants/common.ts
  constants/enum.ts
  constants/payment.ts
  lib/http.ts
  lib/utils.ts
  package.json
  providers/app-provider.tsx
  public/img_payment/COD.webp
  public/img_payment/JCB.png
  public/img_payment/cod.png
  public/img_payment/mastercard.png
  public/img_payment/payment1.png
  public/img_payment/visa-512.webp
  public/img_payment/vnpay.webp
  public/img_payment/vnpaydemo.webp
  services/auth.service.ts
  yarn.lock
Labels: size/XL

#34 fix req brand, reponsive
  components/brands/brand.tsx
  components/cart/card-product-cart.tsx
  components/cart/cart-page.tsx
  components/cart/update-product-cart.tsx
  components/home/home-page.tsx
  package.json
  yarn.lock
Labels: size/M

#35 feat(components): ✨ update creating order action
  apiRequests/cart.ts
  apiRequests/product.ts
  app/(auth)/dang-xuat/page.tsx
  app/(need-authenticated)/chi-tiet-don-hang/layout.tsx
  app/(need-authenticated)/chi-tiet-don-hang/page.tsx
  app/(need-authenticated)/gio-hang/page.tsx
  app/(need-authenticated)/thanh-toan/page.tsx
  app/layout.tsx
  components/cart/card-product-cart.tsx
  components/cart/cart-page.tsx
  components/cart/cart-product-skeleton.tsx
  components/cart/list-product-cart.tsx
  components/common/form/input-text.tsx
  components/navigation/header/header-icon.tsx
  components/order/order-list-product.tsx
  components/order/order-preview.tsx
  components/product/product-detail.tsx
  components/ui/textarea.tsx
  constants/enum.ts
  lib/http.ts
  package.json
  validationSchemas/index.ts
  validationSchemas/payment.schema.ts
  yarn.lock
Labels: size/L

#36 fix responsive
  components/order/address-order.tsx
  components/order/order-list-product.tsx
  components/order/order-preview.tsx
  components/order/payment_method_list.tsx
  components/order/shipping-info-order.tsx
  components/profile/address-list.tsx
Labels: size/L

#37 update UI, fix similar product
  app/(public)/chi-tiet-san-pham/[id]/page.tsx
  app/page.tsx
  components/brands/brandscrolling.tsx
  components/cart/cart-empty.tsx
  components/cart/cart-page.tsx
  components/cart/cart-suggest.tsx
  components/common/product-card/normal-card.tsx
  components/home/banner-page.tsx
  components/home/home-page.tsx
  components/home/list-product-hot.tsx
  components/home/list-product.tsx
  components/product/outstanding-features-product.tsx
  components/product/product-detail.tsx
  components/product/similar-product.tsx
  constants/common.ts
  public/phone-test/a2-9005-1678197385.jpg
  public/phone-test/dien-thoai-iphone-14-plus-128gb-do-1.jpg
  public/phone-test/iPhone-14-pro-mau-xam.jpg
  public/phone-test/iphone-14-promax-trang2-650x650-1.jpg
  public/phone-test/iphone-14-tim
  public/phone-test/iphone-14-xanh
Labels: size/L

#38 feat(components): ✨ update buy now button
  apiRequests/index.ts
  app/(need-authenticated)/thanh-toan/page.tsx
  components/cart/cart-page.tsx
  components/common/product-card/modal-information.tsx
  components/common/product-card/normal-card-button.tsx
  components/common/product-card/normal-card.tsx
  components/common/small-loading.tsx
  components/navigation/header/button-logout.tsx
  components/order/order-list-product.tsx
  components/order/order-preview.tsx
  components/product/button-buy.tsx
  components/product/select-product-variation.tsx
  components/profile/address-form.tsx
  providers/app-provider.tsx
Labels: size/L

#40 Handle buy now
  apiRequests/product.ts
  app/(public)/danh-sach-san-pham/page.tsx
  components/order/order-preview.tsx
  components/order/payment_method_list.tsx
Labels: size/M
