Repository TechCell-Project/techcell-web-client-v2, pull requests merged in 2024-05, with the labels that each got.

#42 feat(app): 🎨 refactored app: auth session + products list
  apiRequests/auth.ts
  apiRequests/cart.ts
  app/(auth)/confirm-email/page.tsx
  app/(auth)/dang-xuat/page.tsx
  app/(auth)/mat-khau-moi/page.tsx
  app/(need-authenticated)/ho-so/page.tsx
  app/(need-authenticated)/thanh-toan/page.tsx
  app/(public)/danh-sach-san-pham/page.tsx
  app/api/auth-client/logout/route.ts
  app/api/auth-client/refresh/route.ts
  app/api/auth-client/route.ts
  app/layout.tsx
  app/page.tsx
  components/auth/auto-refresh-token.tsx
  components/auth/login-form.tsx
  components/auth/social.tsx
  components/common/modals/address-modal.tsx
  components/common/pagination/pagination-bar.tsx
  components/common/product-card/modal-information.tsx
  components/common/product-card/normal-card-button.tsx
  components/common/product-card/normal-card-skeleton.tsx
  components/common/product-card/normal-card.tsx
  components/home/list-product-hot.tsx
  components/navigation/header/button-logout.tsx
  components/navigation/header/header-icon.tsx
  components/navigation/header/index.tsx
  components/products/products-section.tsx
  components/profile/address-form.tsx
  components/profile/address-list.tsx
  components/profile/profile-form.tsx
  components/profile/profile.tsx
  constants/services.ts
  lib/http.ts
  lib/utils.ts
  middleware.ts
  package.json
  providers/app-provider.tsx
  providers/modal-provider.tsx
  yarn.lock
Labels: size/XL

#43 refactor(components): ⚡ remove current user if accessToken is undefined
  app/(need-authenticated)/gio-hang/page.tsx
  components/auth/auto-refresh-token.tsx
  components/common/searchbar/search-bar.tsx
  components/navigation/header/index.tsx
  providers/app-provider.tsx
Labels: size/M

#47 feat(components): ✨ update search bar popover
  .hintrc
  app/(public)/danh-sach-san-pham/page.tsx
  app/globals.css
  components/cart/cart-page.tsx
  components/cart/models/cart.ts
  components/cart/models/index.ts
  components/common/searchbar/search-bar.tsx
  hooks/useIsMobile.ts
  hooks/useRecentSearches.ts
  package.json
  yarn.lock
Labels: size/L

#45 Revised home page
  app/(need-authenticated)/gio-hang/page.tsx
  app/page.tsx
  components/common/product-card/normal-card.tsx
  components/common/product-card/succinct-card.tsx
  components/home/home-page.tsx
  components/home/list-product-hot.tsx
  components/home/list-product.tsx
  components/home/swiper-carousel.tsx
  components/navigation/header/index.tsx
  components/product/product-detail.tsx
  constants/common.ts
  public/carousel-img/new1.png
  public/carousel-img/new2.png
  public/carousel-img/new3.png
  public/hot-sale.jpg
Labels: size/L

#46 refactor(components): ⚡ refactor cart logics
  components/cart/address-cart.tsx
  components/cart/button-cart.tsx
  components/cart/cart-page.tsx
  components/cart/list-product-cart.tsx
  components/cart/table-cart-detail.tsx
  components/cart/table/cart-data-table.tsx
  components/cart/table/cart-table-pagination.tsx
  components/cart/table/columns.tsx
  components/common/data-table/data-table-column-header.tsx
  components/home/home-page.tsx
  components/order/order-preview.tsx
  components/profile/address-form.tsx
  components/profile/address-list.tsx
  package.json
  yarn.lock
Labels: size/XL

#49 feat(app): ✨ update handle order logics
  app/(need-authenticated)/thanh-toan/page.tsx
  app/layout.tsx
  app/page.tsx
  components/auth/auto-refresh-token.tsx
  components/cart/cart-page.tsx
  components/cart/table/cart-data-table.tsx
  components/common/form/input-combobox.tsx
  components/common/searchbar/search-bar.tsx
  components/home/banner-page.tsx
  components/home/list-product.tsx
  components/order/address-order.tsx
  components/order/order-preview.tsx
  components/product/button-buy.tsx
  components/products/load-more.tsx
  components/profile/address-list.tsx
  lib/http.ts
  providers/app-provider.tsx
  providers/order-preview-store-provider.tsx
  stores/order-preview.store.ts
Labels: size/XL

#50 fix(components): 🐛 fix undefined update address in cart
  app/(need-authenticated)/thanh-toan/page.tsx
  components/profile/address-form.tsx
  package.json
  yarn.lock
Labels: size/M

#51 feat(components): ⚡ update demo redirect url when create order
  apiRequests/order.ts
  app/(public)/thuong-hieu/layout.tsx
  app/(public)/thuong-hieu/page.tsx
  app/page.tsx
  components/auth/auto-refresh-token.tsx
  components/cart/table/cart-data-table.tsx
  components/home/list-product-hot.tsx
  components/home/list-product.tsx
  components/order/order-preview.tsx
  lib/http.ts
  package.json
  yarn.lock
Labels: size/L

#54 feat(components): ✨ update orders page
  apiRequests/order.ts
  app/(need-authenticated)/chi-tiet-don-hang/[id]/page.tsx
  app/(need-authenticated)/don-hang/[id]/layout.tsx
  app/(need-authenticated)/don-hang/[id]/page.tsx
  app/(need-authenticated)/don-hang/layout.tsx
  app/(need-authenticated)/don-hang/page.tsx
  app/(need-authenticated)/gio-hang/page.tsx
  app/(public)/chi-tiet-don-hang/layout.tsx
  app/(public)/chi-tiet-don-hang/page.tsx
  app/globals.css
  app/page.tsx
  components/common/pagination/pagination-bar.tsx
  components/navigation/header/header-icon.tsx
  components/navigation/header/index.tsx
  components/order/order-detail.tsx
  components/order/order-list-product.tsx
  components/order/sidebar-order.tsx
  components/orders/order-card.tsx
  components/orders/orders-list.tsx
  components/orders/orders-sidebar.tsx
  components/orders/orders-skeleton.tsx
  constants/common.ts
  constants/enum.ts
  constants/payment.ts
  constants/phone-test.ts
  lib/http.ts
  lib/utils.ts
  middleware.ts
  package.json
  providers/app-provider.tsx
  routes/index.ts
  yarn.lock
Labels: size/XXL

#55 refactor(components): 🎨 update missing buying button of normal card
  components/products/load-more.tsx
  components/products/products-section.tsx
  lib/http.ts
Labels: size/S
